FROM ubuntu:22.04

RUN set -eux; \
    export DEBIAN_FRONTEND=noninteractive; \
    apt-get update; \
    apt-get install -y \
        gettext-base\
        git \
        dpkg-dev; \
    rm -rf /var/lib/apt/lists/*; \
    mkdir /build

WORKDIR /build
