FROM debian:bullseye


RUN set -eux; \
    export DEBIAN_FRONTEND=noninteractive; \
    apt-get update; \
     apt-get install -y \
        gettext-base\
        gcc \
        git \
        libc6-dev \
        libglib2.0-dev \
        libseccomp-dev \
        libsystemd-dev \
        pkg-config \
        make \
        runc \
        dpkg-dev; \
    rm -rf /var/lib/apt/lists/*; \
    mkdir /build

WORKDIR /build
