name: Build Aardvark DNS

on:
  repository_dispatch:
    types: [build-aardvark-dns]

  push:
    paths:
      - 'aardvark-dns/**'

jobs:
  aardvark-dns:
    uses: ./.github/workflows/build.yml
    with:
      github_event_name: ${{ github.event_name }}
      app_name: aardvark-dns
      app_version: ${{ github.event.client_payload.version }}
    secrets:
      token: "${{ secrets.GITHUB_TOKEN }}"
