name: Cron

on:
  schedule:
    - cron:  '30 5 * * *'

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: podman
        run: ./scripts/trigger_builds.sh "${{ github.repository }}"
        env:
          GITHUB_PAT: "${{ secrets.REPO_DISPATCH_PAT }}"
